//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 12:12:30 PM COT 
//


package co.gov.colpensiones.beps.comunes.databaseconfiguration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MetadataParameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MetadataParameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParameterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ParameterType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ParameterScale" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetadataParameter", propOrder = {
    "parameterName",
    "parameterType",
    "parameterScale"
})

/**
 * Estructura para definir un parametro de una sentencia SQL
 * @
 *
 */

public class MetadataParameter {

    @XmlElement(name = "ParameterName", required = true)
    protected String parameterName;
    @XmlElement(name = "ParameterType", required = true)
    protected String parameterType;
    @XmlElement(name = "ParameterScale")
    protected int parameterScale;

    /**
     * Gets the value of the parameterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterName() {
        return parameterName;
    }

    /**
     * Sets the value of the parameterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterName(String value) {
        this.parameterName = value;
    }

    /**
     * Gets the value of the parameterType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterType() {
        return parameterType;
    }

    /**
     * Sets the value of the parameterType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterType(String value) {
        this.parameterType = value;
    }

    /**
     * Gets the value of the parameterScale property.
     * 
     */
    public int getParameterScale() {
        return parameterScale;
    }

    /**
     * Sets the value of the parameterScale property.
     * 
     */
    public void setParameterScale(int value) {
        this.parameterScale = value;
    }

}
