//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 12:12:30 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/DatabaseConfiguration", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.gov.colpensiones.beps.comunes.databaseconfiguration;
